### ISSUE TITLE
Class & Method Detection Too Generic

### ISSUE THREAD

**Issue by Shumaan** [jfrog/text4shell-tools#1]
>  for each printing out locations (class name and method name) of calls to lookup/replace/replaceIn methods of StringSubstitutor/StringLookup.

Correct me if I'm wrong, but this detection is likely too generic and will result in a lot of false positives. Vulnerable code would need  to be using an interpolator via .createInterpolator().

**Comment by ilya-k-1** [comment]
Hi @Shumaan ,
You are correct, there are conditions which are not checked (such as using an interpolator, and the fact that the input to the vulnerable functions may be controlled by an external attacker). While missing these conditions may indeed lead to false positives, they are more tricky to check (especially in compiled code), and therefore relying on these conditions may lead to false negatives. In our perspective, we prefer a simple tool which provides the developers with a complete list of all the places to check (which may be longer than needed in some cases), rather than a more complicated tool which might miss some relevant results and claim that the application is secure when it isn't.
That being said, we will try to improve the tools to give more precise results according to the feedback.
Thanks!

**Comment by Shumaan** [comment]
No worry - just checking. Thanks for the response!
